// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/amq.proto

package amqpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common enums
type QueueType int32

const (
	QueueType_QUEUE_TYPE_UNSPECIFIED QueueType = 0
	QueueType_QUEUE_TYPE_TASK        QueueType = 1
	QueueType_QUEUE_TYPE_DIRECT      QueueType = 2
)

// Enum value maps for QueueType.
var (
	QueueType_name = map[int32]string{
		0: "QUEUE_TYPE_UNSPECIFIED",
		1: "QUEUE_TYPE_TASK",
		2: "QUEUE_TYPE_DIRECT",
	}
	QueueType_value = map[string]int32{
		"QUEUE_TYPE_UNSPECIFIED": 0,
		"QUEUE_TYPE_TASK":        1,
		"QUEUE_TYPE_DIRECT":      2,
	}
)

func (x QueueType) Enum() *QueueType {
	p := new(QueueType)
	*p = x
	return p
}

func (x QueueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_amq_proto_enumTypes[0].Descriptor()
}

func (QueueType) Type() protoreflect.EnumType {
	return &file_api_proto_amq_proto_enumTypes[0]
}

func (x QueueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueType.Descriptor instead.
func (QueueType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{0}
}

type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_UNSPECIFIED  MessageStatus = 0
	MessageStatus_MESSAGE_STATUS_PENDING      MessageStatus = 1
	MessageStatus_MESSAGE_STATUS_DELIVERED    MessageStatus = 2
	MessageStatus_MESSAGE_STATUS_ACKNOWLEDGED MessageStatus = 3
	MessageStatus_MESSAGE_STATUS_FAILED       MessageStatus = 4
	MessageStatus_MESSAGE_STATUS_EXPIRED      MessageStatus = 5
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNSPECIFIED",
		1: "MESSAGE_STATUS_PENDING",
		2: "MESSAGE_STATUS_DELIVERED",
		3: "MESSAGE_STATUS_ACKNOWLEDGED",
		4: "MESSAGE_STATUS_FAILED",
		5: "MESSAGE_STATUS_EXPIRED",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNSPECIFIED":  0,
		"MESSAGE_STATUS_PENDING":      1,
		"MESSAGE_STATUS_DELIVERED":    2,
		"MESSAGE_STATUS_ACKNOWLEDGED": 3,
		"MESSAGE_STATUS_FAILED":       4,
		"MESSAGE_STATUS_EXPIRED":      5,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_amq_proto_enumTypes[1].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_api_proto_amq_proto_enumTypes[1]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{1}
}

// Client management messages
type RegisterClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capabilities  *ClientCapabilities    `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClientRequest) Reset() {
	*x = RegisterClientRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientRequest) ProtoMessage() {}

func (x *RegisterClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientRequest.ProtoReflect.Descriptor instead.
func (*RegisterClientRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegisterClientRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterClientRequest) GetCapabilities() *ClientCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ClientCapabilities struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MaxConcurrentMessages int32                  `protobuf:"varint,1,opt,name=max_concurrent_messages,json=maxConcurrentMessages,proto3" json:"max_concurrent_messages,omitempty"`
	SupportedEncodings    []string               `protobuf:"bytes,2,rep,name=supported_encodings,json=supportedEncodings,proto3" json:"supported_encodings,omitempty"`
	SupportsBatch         bool                   `protobuf:"varint,3,opt,name=supports_batch,json=supportsBatch,proto3" json:"supports_batch,omitempty"`
	PrefetchCount         int32                  `protobuf:"varint,4,opt,name=prefetch_count,json=prefetchCount,proto3" json:"prefetch_count,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClientCapabilities) Reset() {
	*x = ClientCapabilities{}
	mi := &file_api_proto_amq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCapabilities) ProtoMessage() {}

func (x *ClientCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCapabilities.ProtoReflect.Descriptor instead.
func (*ClientCapabilities) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{1}
}

func (x *ClientCapabilities) GetMaxConcurrentMessages() int32 {
	if x != nil {
		return x.MaxConcurrentMessages
	}
	return 0
}

func (x *ClientCapabilities) GetSupportedEncodings() []string {
	if x != nil {
		return x.SupportedEncodings
	}
	return nil
}

func (x *ClientCapabilities) GetSupportsBatch() bool {
	if x != nil {
		return x.SupportsBatch
	}
	return false
}

func (x *ClientCapabilities) GetPrefetchCount() int32 {
	if x != nil {
		return x.PrefetchCount
	}
	return 0
}

type RegisterClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterClientResponse) Reset() {
	*x = RegisterClientResponse{}
	mi := &file_api_proto_amq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientResponse) ProtoMessage() {}

func (x *RegisterClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientResponse.ProtoReflect.Descriptor instead.
func (*RegisterClientResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterClientResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterClientResponse) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

type UnregisterClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterClientRequest) Reset() {
	*x = UnregisterClientRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterClientRequest) ProtoMessage() {}

func (x *UnregisterClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterClientRequest.ProtoReflect.Descriptor instead.
func (*UnregisterClientRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // CPU usage, memory, etc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *HeartbeatRequest) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Queue management messages
type CreateQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          QueueType              `protobuf:"varint,2,opt,name=type,proto3,enum=amq.v1.QueueType" json:"type,omitempty"`
	Config        *QueueConfig           `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQueueRequest) Reset() {
	*x = CreateQueueRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueRequest) ProtoMessage() {}

func (x *CreateQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueRequest.ProtoReflect.Descriptor instead.
func (*CreateQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{5}
}

func (x *CreateQueueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateQueueRequest) GetType() QueueType {
	if x != nil {
		return x.Type
	}
	return QueueType_QUEUE_TYPE_UNSPECIFIED
}

func (x *CreateQueueRequest) GetConfig() *QueueConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type QueueConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MaxDepth         int32                  `protobuf:"varint,1,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	MessageTtl       *durationpb.Duration   `protobuf:"bytes,2,opt,name=message_ttl,json=messageTtl,proto3" json:"message_ttl,omitempty"`
	MaxRetries       int32                  `protobuf:"varint,3,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	EnableDeadLetter bool                   `protobuf:"varint,4,opt,name=enable_dead_letter,json=enableDeadLetter,proto3" json:"enable_dead_letter,omitempty"`
	DeadLetterQueue  string                 `protobuf:"bytes,5,opt,name=dead_letter_queue,json=deadLetterQueue,proto3" json:"dead_letter_queue,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueueConfig) Reset() {
	*x = QueueConfig{}
	mi := &file_api_proto_amq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueConfig) ProtoMessage() {}

func (x *QueueConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueConfig.ProtoReflect.Descriptor instead.
func (*QueueConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{6}
}

func (x *QueueConfig) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *QueueConfig) GetMessageTtl() *durationpb.Duration {
	if x != nil {
		return x.MessageTtl
	}
	return nil
}

func (x *QueueConfig) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *QueueConfig) GetEnableDeadLetter() bool {
	if x != nil {
		return x.EnableDeadLetter
	}
	return false
}

func (x *QueueConfig) GetDeadLetterQueue() string {
	if x != nil {
		return x.DeadLetterQueue
	}
	return ""
}

type CreateQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQueueResponse) Reset() {
	*x = CreateQueueResponse{}
	mi := &file_api_proto_amq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQueueResponse) ProtoMessage() {}

func (x *CreateQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQueueResponse.ProtoReflect.Descriptor instead.
func (*CreateQueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{7}
}

func (x *CreateQueueResponse) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

func (x *CreateQueueResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DeleteQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"` // Delete even if not empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQueueRequest) Reset() {
	*x = DeleteQueueRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQueueRequest) ProtoMessage() {}

func (x *DeleteQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQueueRequest.ProtoReflect.Descriptor instead.
func (*DeleteQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteQueueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteQueueRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ListQueuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesRequest) Reset() {
	*x = ListQueuesRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesRequest) ProtoMessage() {}

func (x *ListQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesRequest.ProtoReflect.Descriptor instead.
func (*ListQueuesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{9}
}

func (x *ListQueuesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListQueuesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListQueuesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListQueuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queues        []*QueueInfo           `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesResponse) Reset() {
	*x = ListQueuesResponse{}
	mi := &file_api_proto_amq_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesResponse) ProtoMessage() {}

func (x *ListQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesResponse.ProtoReflect.Descriptor instead.
func (*ListQueuesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{10}
}

func (x *ListQueuesResponse) GetQueues() []*QueueInfo {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *ListQueuesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type QueueInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type            QueueType              `protobuf:"varint,2,opt,name=type,proto3,enum=amq.v1.QueueType" json:"type,omitempty"`
	MessageCount    int64                  `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	SubscriberCount int32                  `protobuf:"varint,4,opt,name=subscriber_count,json=subscriberCount,proto3" json:"subscriber_count,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueueInfo) Reset() {
	*x = QueueInfo{}
	mi := &file_api_proto_amq_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueInfo) ProtoMessage() {}

func (x *QueueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueInfo.ProtoReflect.Descriptor instead.
func (*QueueInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{11}
}

func (x *QueueInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueInfo) GetType() QueueType {
	if x != nil {
		return x.Type
	}
	return QueueType_QUEUE_TYPE_UNSPECIFIED
}

func (x *QueueInfo) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *QueueInfo) GetSubscriberCount() int32 {
	if x != nil {
		return x.SubscriberCount
	}
	return 0
}

func (x *QueueInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetQueueStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatsRequest) Reset() {
	*x = GetQueueStatsRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatsRequest) ProtoMessage() {}

func (x *GetQueueStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatsRequest.ProtoReflect.Descriptor instead.
func (*GetQueueStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{12}
}

func (x *GetQueueStatsRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type GetQueueStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageCount     int64                  `protobuf:"varint,1,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	MessagesInFlight int64                  `protobuf:"varint,2,opt,name=messages_in_flight,json=messagesInFlight,proto3" json:"messages_in_flight,omitempty"`
	SubscriberCount  int32                  `protobuf:"varint,3,opt,name=subscriber_count,json=subscriberCount,proto3" json:"subscriber_count,omitempty"`
	EnqueueRate      float64                `protobuf:"fixed64,4,opt,name=enqueue_rate,json=enqueueRate,proto3" json:"enqueue_rate,omitempty"` // messages per second
	DequeueRate      float64                `protobuf:"fixed64,5,opt,name=dequeue_rate,json=dequeueRate,proto3" json:"dequeue_rate,omitempty"` // messages per second
	TotalEnqueued    int64                  `protobuf:"varint,6,opt,name=total_enqueued,json=totalEnqueued,proto3" json:"total_enqueued,omitempty"`
	TotalDequeued    int64                  `protobuf:"varint,7,opt,name=total_dequeued,json=totalDequeued,proto3" json:"total_dequeued,omitempty"`
	TotalAcked       int64                  `protobuf:"varint,8,opt,name=total_acked,json=totalAcked,proto3" json:"total_acked,omitempty"`
	OldestMessage    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=oldest_message,json=oldestMessage,proto3" json:"oldest_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetQueueStatsResponse) Reset() {
	*x = GetQueueStatsResponse{}
	mi := &file_api_proto_amq_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatsResponse) ProtoMessage() {}

func (x *GetQueueStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatsResponse.ProtoReflect.Descriptor instead.
func (*GetQueueStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{13}
}

func (x *GetQueueStatsResponse) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *GetQueueStatsResponse) GetMessagesInFlight() int64 {
	if x != nil {
		return x.MessagesInFlight
	}
	return 0
}

func (x *GetQueueStatsResponse) GetSubscriberCount() int32 {
	if x != nil {
		return x.SubscriberCount
	}
	return 0
}

func (x *GetQueueStatsResponse) GetEnqueueRate() float64 {
	if x != nil {
		return x.EnqueueRate
	}
	return 0
}

func (x *GetQueueStatsResponse) GetDequeueRate() float64 {
	if x != nil {
		return x.DequeueRate
	}
	return 0
}

func (x *GetQueueStatsResponse) GetTotalEnqueued() int64 {
	if x != nil {
		return x.TotalEnqueued
	}
	return 0
}

func (x *GetQueueStatsResponse) GetTotalDequeued() int64 {
	if x != nil {
		return x.TotalDequeued
	}
	return 0
}

func (x *GetQueueStatsResponse) GetTotalAcked() int64 {
	if x != nil {
		return x.TotalAcked
	}
	return 0
}

func (x *GetQueueStatsResponse) GetOldestMessage() *timestamppb.Timestamp {
	if x != nil {
		return x.OldestMessage
	}
	return nil
}

// Subscription management
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Options       *SubscriptionOptions   `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *SubscribeRequest) GetOptions() *SubscriptionOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type SubscriptionOptions struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Priority         int32                  `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`                                        // Higher priority clients get messages first
	FilterExpression string                 `protobuf:"bytes,2,opt,name=filter_expression,json=filterExpression,proto3" json:"filter_expression,omitempty"` // Optional message filter
	Exclusive        bool                   `protobuf:"varint,3,opt,name=exclusive,proto3" json:"exclusive,omitempty"`                                      // Only one client receives each message
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubscriptionOptions) Reset() {
	*x = SubscriptionOptions{}
	mi := &file_api_proto_amq_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionOptions) ProtoMessage() {}

func (x *SubscriptionOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionOptions.ProtoReflect.Descriptor instead.
func (*SubscriptionOptions) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{15}
}

func (x *SubscriptionOptions) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubscriptionOptions) GetFilterExpression() string {
	if x != nil {
		return x.FilterExpression
	}
	return ""
}

func (x *SubscriptionOptions) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{16}
}

func (x *UnsubscribeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UnsubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

// Message operations
type SubmitTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Options       *MessageOptions        `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{17}
}

func (x *SubmitTaskRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SubmitTaskRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubmitTaskRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubmitTaskRequest) GetOptions() *MessageOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type MessageOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priority      int32                  `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"` // 0-9, higher is more important
	Ttl           *durationpb.Duration   `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,3,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ReplyTo       string                 `protobuf:"bytes,6,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_api_proto_amq_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{18}
}

func (x *MessageOptions) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *MessageOptions) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *MessageOptions) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *MessageOptions) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MessageOptions) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *MessageOptions) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

type SubmitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_api_proto_amq_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{19}
}

func (x *SubmitTaskResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SubmitTaskResponse) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

type SubmitTaskBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Items         []*TaskItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskBatchRequest) Reset() {
	*x = SubmitTaskBatchRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskBatchRequest) ProtoMessage() {}

func (x *SubmitTaskBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskBatchRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{20}
}

func (x *SubmitTaskBatchRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SubmitTaskBatchRequest) GetItems() []*TaskItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type TaskItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Options       *MessageOptions        `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskItem) Reset() {
	*x = TaskItem{}
	mi := &file_api_proto_amq_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskItem) ProtoMessage() {}

func (x *TaskItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskItem.ProtoReflect.Descriptor instead.
func (*TaskItem) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{21}
}

func (x *TaskItem) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *TaskItem) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskItem) GetOptions() *MessageOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type SubmitTaskBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TaskResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskBatchResponse) Reset() {
	*x = SubmitTaskBatchResponse{}
	mi := &file_api_proto_amq_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskBatchResponse) ProtoMessage() {}

func (x *SubmitTaskBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskBatchResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskBatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{22}
}

func (x *SubmitTaskBatchResponse) GetResults() []*TaskResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_api_proto_amq_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{23}
}

func (x *TaskResult) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SendDirectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromClientId  string                 `protobuf:"bytes,1,opt,name=from_client_id,json=fromClientId,proto3" json:"from_client_id,omitempty"`
	ToClientId    string                 `protobuf:"bytes,2,opt,name=to_client_id,json=toClientId,proto3" json:"to_client_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Options       *MessageOptions        `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDirectRequest) Reset() {
	*x = SendDirectRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDirectRequest) ProtoMessage() {}

func (x *SendDirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDirectRequest.ProtoReflect.Descriptor instead.
func (*SendDirectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{24}
}

func (x *SendDirectRequest) GetFromClientId() string {
	if x != nil {
		return x.FromClientId
	}
	return ""
}

func (x *SendDirectRequest) GetToClientId() string {
	if x != nil {
		return x.ToClientId
	}
	return ""
}

func (x *SendDirectRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendDirectRequest) GetOptions() *MessageOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type SendDirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDirectResponse) Reset() {
	*x = SendDirectResponse{}
	mi := &file_api_proto_amq_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDirectResponse) ProtoMessage() {}

func (x *SendDirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDirectResponse.ProtoReflect.Descriptor instead.
func (*SendDirectResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{25}
}

func (x *SendDirectResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendDirectResponse) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type ReceiveMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MaxMessages   int32                  `protobuf:"varint,2,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"`
	WaitTime      *durationpb.Duration   `protobuf:"bytes,3,opt,name=wait_time,json=waitTime,proto3" json:"wait_time,omitempty"` // Long polling
	AutoAck       bool                   `protobuf:"varint,4,opt,name=auto_ack,json=autoAck,proto3" json:"auto_ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveMessagesRequest) Reset() {
	*x = ReceiveMessagesRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMessagesRequest) ProtoMessage() {}

func (x *ReceiveMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMessagesRequest.ProtoReflect.Descriptor instead.
func (*ReceiveMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{26}
}

func (x *ReceiveMessagesRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ReceiveMessagesRequest) GetMaxMessages() int32 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

func (x *ReceiveMessagesRequest) GetWaitTime() *durationpb.Duration {
	if x != nil {
		return x.WaitTime
	}
	return nil
}

func (x *ReceiveMessagesRequest) GetAutoAck() bool {
	if x != nil {
		return x.AutoAck
	}
	return false
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromClientId  string                 `protobuf:"bytes,2,opt,name=from_client_id,json=fromClientId,proto3" json:"from_client_id,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Status        MessageStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=amq.v1.MessageStatus" json:"status,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	RetryCount    int32                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CorrelationId string                 `protobuf:"bytes,11,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ReplyTo       string                 `protobuf:"bytes,12,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_proto_amq_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{27}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetFromClientId() string {
	if x != nil {
		return x.FromClientId
	}
	return ""
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

func (x *Message) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Message) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Message) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Message) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

type AckMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessageRequest) Reset() {
	*x = AckMessageRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageRequest) ProtoMessage() {}

func (x *AckMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageRequest.ProtoReflect.Descriptor instead.
func (*AckMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{28}
}

func (x *AckMessageRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AckMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type AckMessageBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MessageIds    []string               `protobuf:"bytes,2,rep,name=message_ids,json=messageIds,proto3" json:"message_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMessageBatchRequest) Reset() {
	*x = AckMessageBatchRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessageBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessageBatchRequest) ProtoMessage() {}

func (x *AckMessageBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessageBatchRequest.ProtoReflect.Descriptor instead.
func (*AckMessageBatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{29}
}

func (x *AckMessageBatchRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AckMessageBatchRequest) GetMessageIds() []string {
	if x != nil {
		return x.MessageIds
	}
	return nil
}

type NackMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Requeue       bool                   `protobuf:"varint,3,opt,name=requeue,proto3" json:"requeue,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackMessageRequest) Reset() {
	*x = NackMessageRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackMessageRequest) ProtoMessage() {}

func (x *NackMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackMessageRequest.ProtoReflect.Descriptor instead.
func (*NackMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{30}
}

func (x *NackMessageRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *NackMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *NackMessageRequest) GetRequeue() bool {
	if x != nil {
		return x.Requeue
	}
	return false
}

func (x *NackMessageRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Client info
type ClientInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RegisteredAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastSeen         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Subscriptions    []string               `protobuf:"bytes,5,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	MessagesSent     int64                  `protobuf:"varint,6,opt,name=messages_sent,json=messagesSent,proto3" json:"messages_sent,omitempty"`
	MessagesReceived int64                  `protobuf:"varint,7,opt,name=messages_received,json=messagesReceived,proto3" json:"messages_received,omitempty"`
	Capabilities     *ClientCapabilities    `protobuf:"bytes,8,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_api_proto_amq_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{31}
}

func (x *ClientInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClientInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClientInfo) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *ClientInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *ClientInfo) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *ClientInfo) GetMessagesSent() int64 {
	if x != nil {
		return x.MessagesSent
	}
	return 0
}

func (x *ClientInfo) GetMessagesReceived() int64 {
	if x != nil {
		return x.MessagesReceived
	}
	return 0
}

func (x *ClientInfo) GetCapabilities() *ClientCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type GetClientInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientInfoRequest) Reset() {
	*x = GetClientInfoRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientInfoRequest) ProtoMessage() {}

func (x *GetClientInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientInfoRequest.ProtoReflect.Descriptor instead.
func (*GetClientInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{32}
}

func (x *GetClientInfoRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type ListClientsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FilterMetadata map[string]string      `protobuf:"bytes,1,rep,name=filter_metadata,json=filterMetadata,proto3" json:"filter_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListClientsRequest) Reset() {
	*x = ListClientsRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsRequest) ProtoMessage() {}

func (x *ListClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsRequest.ProtoReflect.Descriptor instead.
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{33}
}

func (x *ListClientsRequest) GetFilterMetadata() map[string]string {
	if x != nil {
		return x.FilterMetadata
	}
	return nil
}

func (x *ListClientsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListClientsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*ClientInfo          `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
	mi := &file_api_proto_amq_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsResponse.ProtoReflect.Descriptor instead.
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{34}
}

func (x *ListClientsResponse) GetClients() []*ClientInfo {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *ListClientsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Monitoring
type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricNames   []string               `protobuf:"bytes,1,rep,name=metric_names,json=metricNames,proto3" json:"metric_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_api_proto_amq_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{35}
}

func (x *GetMetricsRequest) GetMetricNames() []string {
	if x != nil {
		return x.MetricNames
	}
	return nil
}

type MetricsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Metrics       map[string]*MetricValue `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_api_proto_amq_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{36}
}

func (x *MetricsResponse) GetMetrics() map[string]*MetricValue {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *MetricsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type MetricValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*MetricValue_IntValue
	//	*MetricValue_DoubleValue
	//	*MetricValue_StringValue
	Value         isMetricValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricValue) Reset() {
	*x = MetricValue{}
	mi := &file_api_proto_amq_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricValue) ProtoMessage() {}

func (x *MetricValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_amq_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricValue.ProtoReflect.Descriptor instead.
func (*MetricValue) Descriptor() ([]byte, []int) {
	return file_api_proto_amq_proto_rawDescGZIP(), []int{37}
}

func (x *MetricValue) GetValue() isMetricValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MetricValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*MetricValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *MetricValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*MetricValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *MetricValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*MetricValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

type isMetricValue_Value interface {
	isMetricValue_Value()
}

type MetricValue_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type MetricValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type MetricValue_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*MetricValue_IntValue) isMetricValue_Value() {}

func (*MetricValue_DoubleValue) isMetricValue_Value() {}

func (*MetricValue_StringValue) isMetricValue_Value() {}

var File_api_proto_amq_proto protoreflect.FileDescriptor

const file_api_proto_amq_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/amq.proto\x12\x06amq.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xfa\x01\n" +
	"\x15RegisterClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12G\n" +
	"\bmetadata\x18\x02 \x03(\v2+.amq.v1.RegisterClientRequest.MetadataEntryR\bmetadata\x12>\n" +
	"\fcapabilities\x18\x03 \x01(\v2\x1a.amq.v1.ClientCapabilitiesR\fcapabilities\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x12ClientCapabilities\x126\n" +
	"\x17max_concurrent_messages\x18\x01 \x01(\x05R\x15maxConcurrentMessages\x12/\n" +
	"\x13supported_encodings\x18\x02 \x03(\tR\x12supportedEncodings\x12%\n" +
	"\x0esupports_batch\x18\x03 \x01(\bR\rsupportsBatch\x12%\n" +
	"\x0eprefetch_count\x18\x04 \x01(\x05R\rprefetchCount\"x\n" +
	"\x16RegisterClientResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12?\n" +
	"\rregistered_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\"6\n" +
	"\x17UnregisterClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xac\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12?\n" +
	"\ametrics\x18\x02 \x03(\v2%.amq.v1.HeartbeatRequest.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"|\n" +
	"\x12CreateQueueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.amq.v1.QueueTypeR\x04type\x12+\n" +
	"\x06config\x18\x03 \x01(\v2\x13.amq.v1.QueueConfigR\x06config\"\xe1\x01\n" +
	"\vQueueConfig\x12\x1b\n" +
	"\tmax_depth\x18\x01 \x01(\x05R\bmaxDepth\x12:\n" +
	"\vmessage_ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"messageTtl\x12\x1f\n" +
	"\vmax_retries\x18\x03 \x01(\x05R\n" +
	"maxRetries\x12,\n" +
	"\x12enable_dead_letter\x18\x04 \x01(\bR\x10enableDeadLetter\x12*\n" +
	"\x11dead_letter_queue\x18\x05 \x01(\tR\x0fdeadLetterQueue\"k\n" +
	"\x13CreateQueueResponse\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\">\n" +
	"\x12DeleteQueueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"g\n" +
	"\x11ListQueuesRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"g\n" +
	"\x12ListQueuesResponse\x12)\n" +
	"\x06queues\x18\x01 \x03(\v2\x11.amq.v1.QueueInfoR\x06queues\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xd1\x01\n" +
	"\tQueueInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.amq.v1.QueueTypeR\x04type\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x03R\fmessageCount\x12)\n" +
	"\x10subscriber_count\x18\x04 \x01(\x05R\x0fsubscriberCount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"5\n" +
	"\x14GetQueueStatsRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\"\x8d\x03\n" +
	"\x15GetQueueStatsResponse\x12#\n" +
	"\rmessage_count\x18\x01 \x01(\x03R\fmessageCount\x12,\n" +
	"\x12messages_in_flight\x18\x02 \x01(\x03R\x10messagesInFlight\x12)\n" +
	"\x10subscriber_count\x18\x03 \x01(\x05R\x0fsubscriberCount\x12!\n" +
	"\fenqueue_rate\x18\x04 \x01(\x01R\venqueueRate\x12!\n" +
	"\fdequeue_rate\x18\x05 \x01(\x01R\vdequeueRate\x12%\n" +
	"\x0etotal_enqueued\x18\x06 \x01(\x03R\rtotalEnqueued\x12%\n" +
	"\x0etotal_dequeued\x18\a \x01(\x03R\rtotalDequeued\x12\x1f\n" +
	"\vtotal_acked\x18\b \x01(\x03R\n" +
	"totalAcked\x12A\n" +
	"\x0eoldest_message\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\roldestMessage\"~\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\x125\n" +
	"\aoptions\x18\x03 \x01(\v2\x1b.amq.v1.SubscriptionOptionsR\aoptions\"|\n" +
	"\x13SubscriptionOptions\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\x05R\bpriority\x12+\n" +
	"\x11filter_expression\x18\x02 \x01(\tR\x10filterExpression\x12\x1c\n" +
	"\texclusive\x18\x03 \x01(\bR\texclusive\"I\n" +
	"\x12UnsubscribeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\"\x92\x01\n" +
	"\x11SubmitTaskRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x120\n" +
	"\aoptions\x18\x04 \x01(\v2\x16.amq.v1.MessageOptionsR\aoptions\"\xbb\x02\n" +
	"\x0eMessageOptions\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\x05R\bpriority\x12+\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12\x1f\n" +
	"\vmax_retries\x18\x03 \x01(\x05R\n" +
	"maxRetries\x12@\n" +
	"\bmetadata\x18\x04 \x03(\v2$.amq.v1.MessageOptions.MetadataEntryR\bmetadata\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\breply_to\x18\x06 \x01(\tR\areplyTo\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x12SubmitTaskResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12=\n" +
	"\fsubmitted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\"]\n" +
	"\x16SubmitTaskBatchRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12&\n" +
	"\x05items\x18\x02 \x03(\v2\x10.amq.v1.TaskItemR\x05items\"l\n" +
	"\bTaskItem\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x120\n" +
	"\aoptions\x18\x03 \x01(\v2\x16.amq.v1.MessageOptionsR\aoptions\"G\n" +
	"\x17SubmitTaskBatchResponse\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.amq.v1.TaskResultR\aresults\"[\n" +
	"\n" +
	"TaskResult\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xa7\x01\n" +
	"\x11SendDirectRequest\x12$\n" +
	"\x0efrom_client_id\x18\x01 \x01(\tR\ffromClientId\x12 \n" +
	"\fto_client_id\x18\x02 \x01(\tR\n" +
	"toClientId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x120\n" +
	"\aoptions\x18\x04 \x01(\v2\x16.amq.v1.MessageOptionsR\aoptions\"h\n" +
	"\x12SendDirectResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\xab\x01\n" +
	"\x16ReceiveMessagesRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12!\n" +
	"\fmax_messages\x18\x02 \x01(\x05R\vmaxMessages\x126\n" +
	"\twait_time\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bwaitTime\x12\x19\n" +
	"\bauto_ack\x18\x04 \x01(\bR\aautoAck\"\x8b\x04\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0efrom_client_id\x18\x02 \x01(\tR\ffromClientId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.amq.v1.MessageStatusR\x06status\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\x05R\n" +
	"retryCount\x129\n" +
	"\bmetadata\x18\b \x03(\v2\x1d.amq.v1.Message.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12%\n" +
	"\x0ecorrelation_id\x18\v \x01(\tR\rcorrelationId\x12\x19\n" +
	"\breply_to\x18\f \x01(\tR\areplyTo\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x11AckMessageRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"V\n" +
	"\x16AckMessageBatchRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vmessage_ids\x18\x02 \x03(\tR\n" +
	"messageIds\"\x82\x01\n" +
	"\x12NackMessageRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x18\n" +
	"\arequeue\x18\x03 \x01(\bR\arequeue\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xc9\x03\n" +
	"\n" +
	"ClientInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12<\n" +
	"\bmetadata\x18\x02 \x03(\v2 .amq.v1.ClientInfo.MetadataEntryR\bmetadata\x12?\n" +
	"\rregistered_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x127\n" +
	"\tlast_seen\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12$\n" +
	"\rsubscriptions\x18\x05 \x03(\tR\rsubscriptions\x12#\n" +
	"\rmessages_sent\x18\x06 \x01(\x03R\fmessagesSent\x12+\n" +
	"\x11messages_received\x18\a \x01(\x03R\x10messagesReceived\x12>\n" +
	"\fcapabilities\x18\b \x01(\v2\x1a.amq.v1.ClientCapabilitiesR\fcapabilities\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\x14GetClientInfoRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xec\x01\n" +
	"\x12ListClientsRequest\x12W\n" +
	"\x0ffilter_metadata\x18\x01 \x03(\v2..amq.v1.ListClientsRequest.FilterMetadataEntryR\x0efilterMetadata\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x1aA\n" +
	"\x13FilterMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x13ListClientsResponse\x12,\n" +
	"\aclients\x18\x01 \x03(\v2\x12.amq.v1.ClientInfoR\aclients\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"6\n" +
	"\x11GetMetricsRequest\x12!\n" +
	"\fmetric_names\x18\x01 \x03(\tR\vmetricNames\"\xdc\x01\n" +
	"\x0fMetricsResponse\x12>\n" +
	"\ametrics\x18\x01 \x03(\v2$.amq.v1.MetricsResponse.MetricsEntryR\ametrics\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1aO\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.amq.v1.MetricValueR\x05value:\x028\x01\"\x7f\n" +
	"\vMetricValue\x12\x1d\n" +
	"\tint_value\x18\x01 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x02 \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValueB\a\n" +
	"\x05value*S\n" +
	"\tQueueType\x12\x1a\n" +
	"\x16QUEUE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fQUEUE_TYPE_TASK\x10\x01\x12\x15\n" +
	"\x11QUEUE_TYPE_DIRECT\x10\x02*\xc1\x01\n" +
	"\rMessageStatus\x12\x1e\n" +
	"\x1aMESSAGE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MESSAGE_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18MESSAGE_STATUS_DELIVERED\x10\x02\x12\x1f\n" +
	"\x1bMESSAGE_STATUS_ACKNOWLEDGED\x10\x03\x12\x19\n" +
	"\x15MESSAGE_STATUS_FAILED\x10\x04\x12\x1a\n" +
	"\x16MESSAGE_STATUS_EXPIRED\x10\x052\xc2\n" +
	"\n" +
	"\x03AMQ\x12O\n" +
	"\x0eRegisterClient\x12\x1d.amq.v1.RegisterClientRequest\x1a\x1e.amq.v1.RegisterClientResponse\x12K\n" +
	"\x10UnregisterClient\x12\x1f.amq.v1.UnregisterClientRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\tHeartbeat\x12\x18.amq.v1.HeartbeatRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\vCreateQueue\x12\x1a.amq.v1.CreateQueueRequest\x1a\x1b.amq.v1.CreateQueueResponse\x12A\n" +
	"\vDeleteQueue\x12\x1a.amq.v1.DeleteQueueRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\n" +
	"ListQueues\x12\x19.amq.v1.ListQueuesRequest\x1a\x1a.amq.v1.ListQueuesResponse\x12L\n" +
	"\rGetQueueStats\x12\x1c.amq.v1.GetQueueStatsRequest\x1a\x1d.amq.v1.GetQueueStatsResponse\x12=\n" +
	"\tSubscribe\x12\x18.amq.v1.SubscribeRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\vUnsubscribe\x12\x1a.amq.v1.UnsubscribeRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\n" +
	"SubmitTask\x12\x19.amq.v1.SubmitTaskRequest\x1a\x1a.amq.v1.SubmitTaskResponse\x12C\n" +
	"\n" +
	"SendDirect\x12\x19.amq.v1.SendDirectRequest\x1a\x1a.amq.v1.SendDirectResponse\x12D\n" +
	"\x0fReceiveMessages\x12\x1e.amq.v1.ReceiveMessagesRequest\x1a\x0f.amq.v1.Message0\x01\x12?\n" +
	"\n" +
	"AckMessage\x12\x19.amq.v1.AckMessageRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\vNackMessage\x12\x1a.amq.v1.NackMessageRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x0fSubmitTaskBatch\x12\x1e.amq.v1.SubmitTaskBatchRequest\x1a\x1f.amq.v1.SubmitTaskBatchResponse\x12I\n" +
	"\x0fAckMessageBatch\x12\x1e.amq.v1.AckMessageBatchRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\rGetClientInfo\x12\x1c.amq.v1.GetClientInfoRequest\x1a\x12.amq.v1.ClientInfo\x12F\n" +
	"\vListClients\x12\x1a.amq.v1.ListClientsRequest\x1a\x1b.amq.v1.ListClientsResponse\x12@\n" +
	"\n" +
	"GetMetrics\x12\x19.amq.v1.GetMetricsRequest\x1a\x17.amq.v1.MetricsResponseB+Z)github.com/rizome-dev/amq/api/proto;amqpbb\x06proto3"

var (
	file_api_proto_amq_proto_rawDescOnce sync.Once
	file_api_proto_amq_proto_rawDescData []byte
)

func file_api_proto_amq_proto_rawDescGZIP() []byte {
	file_api_proto_amq_proto_rawDescOnce.Do(func() {
		file_api_proto_amq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_amq_proto_rawDesc), len(file_api_proto_amq_proto_rawDesc)))
	})
	return file_api_proto_amq_proto_rawDescData
}

var file_api_proto_amq_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_amq_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_api_proto_amq_proto_goTypes = []any{
	(QueueType)(0),                  // 0: amq.v1.QueueType
	(MessageStatus)(0),              // 1: amq.v1.MessageStatus
	(*RegisterClientRequest)(nil),   // 2: amq.v1.RegisterClientRequest
	(*ClientCapabilities)(nil),      // 3: amq.v1.ClientCapabilities
	(*RegisterClientResponse)(nil),  // 4: amq.v1.RegisterClientResponse
	(*UnregisterClientRequest)(nil), // 5: amq.v1.UnregisterClientRequest
	(*HeartbeatRequest)(nil),        // 6: amq.v1.HeartbeatRequest
	(*CreateQueueRequest)(nil),      // 7: amq.v1.CreateQueueRequest
	(*QueueConfig)(nil),             // 8: amq.v1.QueueConfig
	(*CreateQueueResponse)(nil),     // 9: amq.v1.CreateQueueResponse
	(*DeleteQueueRequest)(nil),      // 10: amq.v1.DeleteQueueRequest
	(*ListQueuesRequest)(nil),       // 11: amq.v1.ListQueuesRequest
	(*ListQueuesResponse)(nil),      // 12: amq.v1.ListQueuesResponse
	(*QueueInfo)(nil),               // 13: amq.v1.QueueInfo
	(*GetQueueStatsRequest)(nil),    // 14: amq.v1.GetQueueStatsRequest
	(*GetQueueStatsResponse)(nil),   // 15: amq.v1.GetQueueStatsResponse
	(*SubscribeRequest)(nil),        // 16: amq.v1.SubscribeRequest
	(*SubscriptionOptions)(nil),     // 17: amq.v1.SubscriptionOptions
	(*UnsubscribeRequest)(nil),      // 18: amq.v1.UnsubscribeRequest
	(*SubmitTaskRequest)(nil),       // 19: amq.v1.SubmitTaskRequest
	(*MessageOptions)(nil),          // 20: amq.v1.MessageOptions
	(*SubmitTaskResponse)(nil),      // 21: amq.v1.SubmitTaskResponse
	(*SubmitTaskBatchRequest)(nil),  // 22: amq.v1.SubmitTaskBatchRequest
	(*TaskItem)(nil),                // 23: amq.v1.TaskItem
	(*SubmitTaskBatchResponse)(nil), // 24: amq.v1.SubmitTaskBatchResponse
	(*TaskResult)(nil),              // 25: amq.v1.TaskResult
	(*SendDirectRequest)(nil),       // 26: amq.v1.SendDirectRequest
	(*SendDirectResponse)(nil),      // 27: amq.v1.SendDirectResponse
	(*ReceiveMessagesRequest)(nil),  // 28: amq.v1.ReceiveMessagesRequest
	(*Message)(nil),                 // 29: amq.v1.Message
	(*AckMessageRequest)(nil),       // 30: amq.v1.AckMessageRequest
	(*AckMessageBatchRequest)(nil),  // 31: amq.v1.AckMessageBatchRequest
	(*NackMessageRequest)(nil),      // 32: amq.v1.NackMessageRequest
	(*ClientInfo)(nil),              // 33: amq.v1.ClientInfo
	(*GetClientInfoRequest)(nil),    // 34: amq.v1.GetClientInfoRequest
	(*ListClientsRequest)(nil),      // 35: amq.v1.ListClientsRequest
	(*ListClientsResponse)(nil),     // 36: amq.v1.ListClientsResponse
	(*GetMetricsRequest)(nil),       // 37: amq.v1.GetMetricsRequest
	(*MetricsResponse)(nil),         // 38: amq.v1.MetricsResponse
	(*MetricValue)(nil),             // 39: amq.v1.MetricValue
	nil,                             // 40: amq.v1.RegisterClientRequest.MetadataEntry
	nil,                             // 41: amq.v1.HeartbeatRequest.MetricsEntry
	nil,                             // 42: amq.v1.MessageOptions.MetadataEntry
	nil,                             // 43: amq.v1.Message.MetadataEntry
	nil,                             // 44: amq.v1.ClientInfo.MetadataEntry
	nil,                             // 45: amq.v1.ListClientsRequest.FilterMetadataEntry
	nil,                             // 46: amq.v1.MetricsResponse.MetricsEntry
	(*timestamppb.Timestamp)(nil),   // 47: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),     // 48: google.protobuf.Duration
	(*emptypb.Empty)(nil),           // 49: google.protobuf.Empty
}
var file_api_proto_amq_proto_depIdxs = []int32{
	40, // 0: amq.v1.RegisterClientRequest.metadata:type_name -> amq.v1.RegisterClientRequest.MetadataEntry
	3,  // 1: amq.v1.RegisterClientRequest.capabilities:type_name -> amq.v1.ClientCapabilities
	47, // 2: amq.v1.RegisterClientResponse.registered_at:type_name -> google.protobuf.Timestamp
	41, // 3: amq.v1.HeartbeatRequest.metrics:type_name -> amq.v1.HeartbeatRequest.MetricsEntry
	0,  // 4: amq.v1.CreateQueueRequest.type:type_name -> amq.v1.QueueType
	8,  // 5: amq.v1.CreateQueueRequest.config:type_name -> amq.v1.QueueConfig
	48, // 6: amq.v1.QueueConfig.message_ttl:type_name -> google.protobuf.Duration
	47, // 7: amq.v1.CreateQueueResponse.created_at:type_name -> google.protobuf.Timestamp
	13, // 8: amq.v1.ListQueuesResponse.queues:type_name -> amq.v1.QueueInfo
	0,  // 9: amq.v1.QueueInfo.type:type_name -> amq.v1.QueueType
	47, // 10: amq.v1.QueueInfo.created_at:type_name -> google.protobuf.Timestamp
	47, // 11: amq.v1.GetQueueStatsResponse.oldest_message:type_name -> google.protobuf.Timestamp
	17, // 12: amq.v1.SubscribeRequest.options:type_name -> amq.v1.SubscriptionOptions
	20, // 13: amq.v1.SubmitTaskRequest.options:type_name -> amq.v1.MessageOptions
	48, // 14: amq.v1.MessageOptions.ttl:type_name -> google.protobuf.Duration
	42, // 15: amq.v1.MessageOptions.metadata:type_name -> amq.v1.MessageOptions.MetadataEntry
	47, // 16: amq.v1.SubmitTaskResponse.submitted_at:type_name -> google.protobuf.Timestamp
	23, // 17: amq.v1.SubmitTaskBatchRequest.items:type_name -> amq.v1.TaskItem
	20, // 18: amq.v1.TaskItem.options:type_name -> amq.v1.MessageOptions
	25, // 19: amq.v1.SubmitTaskBatchResponse.results:type_name -> amq.v1.TaskResult
	20, // 20: amq.v1.SendDirectRequest.options:type_name -> amq.v1.MessageOptions
	47, // 21: amq.v1.SendDirectResponse.sent_at:type_name -> google.protobuf.Timestamp
	48, // 22: amq.v1.ReceiveMessagesRequest.wait_time:type_name -> google.protobuf.Duration
	1,  // 23: amq.v1.Message.status:type_name -> amq.v1.MessageStatus
	43, // 24: amq.v1.Message.metadata:type_name -> amq.v1.Message.MetadataEntry
	47, // 25: amq.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	47, // 26: amq.v1.Message.expires_at:type_name -> google.protobuf.Timestamp
	44, // 27: amq.v1.ClientInfo.metadata:type_name -> amq.v1.ClientInfo.MetadataEntry
	47, // 28: amq.v1.ClientInfo.registered_at:type_name -> google.protobuf.Timestamp
	47, // 29: amq.v1.ClientInfo.last_seen:type_name -> google.protobuf.Timestamp
	3,  // 30: amq.v1.ClientInfo.capabilities:type_name -> amq.v1.ClientCapabilities
	45, // 31: amq.v1.ListClientsRequest.filter_metadata:type_name -> amq.v1.ListClientsRequest.FilterMetadataEntry
	33, // 32: amq.v1.ListClientsResponse.clients:type_name -> amq.v1.ClientInfo
	46, // 33: amq.v1.MetricsResponse.metrics:type_name -> amq.v1.MetricsResponse.MetricsEntry
	47, // 34: amq.v1.MetricsResponse.timestamp:type_name -> google.protobuf.Timestamp
	39, // 35: amq.v1.MetricsResponse.MetricsEntry.value:type_name -> amq.v1.MetricValue
	2,  // 36: amq.v1.AMQ.RegisterClient:input_type -> amq.v1.RegisterClientRequest
	5,  // 37: amq.v1.AMQ.UnregisterClient:input_type -> amq.v1.UnregisterClientRequest
	6,  // 38: amq.v1.AMQ.Heartbeat:input_type -> amq.v1.HeartbeatRequest
	7,  // 39: amq.v1.AMQ.CreateQueue:input_type -> amq.v1.CreateQueueRequest
	10, // 40: amq.v1.AMQ.DeleteQueue:input_type -> amq.v1.DeleteQueueRequest
	11, // 41: amq.v1.AMQ.ListQueues:input_type -> amq.v1.ListQueuesRequest
	14, // 42: amq.v1.AMQ.GetQueueStats:input_type -> amq.v1.GetQueueStatsRequest
	16, // 43: amq.v1.AMQ.Subscribe:input_type -> amq.v1.SubscribeRequest
	18, // 44: amq.v1.AMQ.Unsubscribe:input_type -> amq.v1.UnsubscribeRequest
	19, // 45: amq.v1.AMQ.SubmitTask:input_type -> amq.v1.SubmitTaskRequest
	26, // 46: amq.v1.AMQ.SendDirect:input_type -> amq.v1.SendDirectRequest
	28, // 47: amq.v1.AMQ.ReceiveMessages:input_type -> amq.v1.ReceiveMessagesRequest
	30, // 48: amq.v1.AMQ.AckMessage:input_type -> amq.v1.AckMessageRequest
	32, // 49: amq.v1.AMQ.NackMessage:input_type -> amq.v1.NackMessageRequest
	22, // 50: amq.v1.AMQ.SubmitTaskBatch:input_type -> amq.v1.SubmitTaskBatchRequest
	31, // 51: amq.v1.AMQ.AckMessageBatch:input_type -> amq.v1.AckMessageBatchRequest
	34, // 52: amq.v1.AMQ.GetClientInfo:input_type -> amq.v1.GetClientInfoRequest
	35, // 53: amq.v1.AMQ.ListClients:input_type -> amq.v1.ListClientsRequest
	37, // 54: amq.v1.AMQ.GetMetrics:input_type -> amq.v1.GetMetricsRequest
	4,  // 55: amq.v1.AMQ.RegisterClient:output_type -> amq.v1.RegisterClientResponse
	49, // 56: amq.v1.AMQ.UnregisterClient:output_type -> google.protobuf.Empty
	49, // 57: amq.v1.AMQ.Heartbeat:output_type -> google.protobuf.Empty
	9,  // 58: amq.v1.AMQ.CreateQueue:output_type -> amq.v1.CreateQueueResponse
	49, // 59: amq.v1.AMQ.DeleteQueue:output_type -> google.protobuf.Empty
	12, // 60: amq.v1.AMQ.ListQueues:output_type -> amq.v1.ListQueuesResponse
	15, // 61: amq.v1.AMQ.GetQueueStats:output_type -> amq.v1.GetQueueStatsResponse
	49, // 62: amq.v1.AMQ.Subscribe:output_type -> google.protobuf.Empty
	49, // 63: amq.v1.AMQ.Unsubscribe:output_type -> google.protobuf.Empty
	21, // 64: amq.v1.AMQ.SubmitTask:output_type -> amq.v1.SubmitTaskResponse
	27, // 65: amq.v1.AMQ.SendDirect:output_type -> amq.v1.SendDirectResponse
	29, // 66: amq.v1.AMQ.ReceiveMessages:output_type -> amq.v1.Message
	49, // 67: amq.v1.AMQ.AckMessage:output_type -> google.protobuf.Empty
	49, // 68: amq.v1.AMQ.NackMessage:output_type -> google.protobuf.Empty
	24, // 69: amq.v1.AMQ.SubmitTaskBatch:output_type -> amq.v1.SubmitTaskBatchResponse
	49, // 70: amq.v1.AMQ.AckMessageBatch:output_type -> google.protobuf.Empty
	33, // 71: amq.v1.AMQ.GetClientInfo:output_type -> amq.v1.ClientInfo
	36, // 72: amq.v1.AMQ.ListClients:output_type -> amq.v1.ListClientsResponse
	38, // 73: amq.v1.AMQ.GetMetrics:output_type -> amq.v1.MetricsResponse
	55, // [55:74] is the sub-list for method output_type
	36, // [36:55] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_api_proto_amq_proto_init() }
func file_api_proto_amq_proto_init() {
	if File_api_proto_amq_proto != nil {
		return
	}
	file_api_proto_amq_proto_msgTypes[37].OneofWrappers = []any{
		(*MetricValue_IntValue)(nil),
		(*MetricValue_DoubleValue)(nil),
		(*MetricValue_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_amq_proto_rawDesc), len(file_api_proto_amq_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_amq_proto_goTypes,
		DependencyIndexes: file_api_proto_amq_proto_depIdxs,
		EnumInfos:         file_api_proto_amq_proto_enumTypes,
		MessageInfos:      file_api_proto_amq_proto_msgTypes,
	}.Build()
	File_api_proto_amq_proto = out.File
	file_api_proto_amq_proto_goTypes = nil
	file_api_proto_amq_proto_depIdxs = nil
}
