# Default values for amq.

replicaCount: 3

image:
  repository: rizome/amq
  pullPolicy: IfNotPresent
  tag: ""  # Overrides the image tag whose default is the chart appVersion

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080
  annotations: {}

# AMQ Configuration
config:
  storePath: "/data/amq"
  workerPoolSize: 10
  heartbeatInterval: "30s"
  messageTimeout: "5m"
  logLevel: "info"

# Persistence configuration
persistence:
  enabled: true
  storageClass: ""  # Use default storage class if not specified
  accessMode: ReadWriteOnce
  size: 10Gi
  annotations: {}

# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Node selector for pod assignment
nodeSelector: {}

# Tolerations for pod assignment
tolerations: []

# Affinity rules for pod assignment
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - amq
        topologyKey: kubernetes.io/hostname

# Probes configuration
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Monitoring
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    interval: 30s
    path: /metrics
    labels: {}

# Network policies
networkPolicy:
  enabled: false
  ingress:
    - from:
      - podSelector:
          matchLabels:
            amq-client: "true"
      ports:
      - protocol: TCP
        port: 8080

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 2

# Extra environment variables
extraEnvVars: []
# - name: EXTRA_VAR
#   value: "extra-value"

# Extra volumes
extraVolumes: []
# - name: extra-volume
#   configMap:
#     name: extra-configmap

# Extra volume mounts
extraVolumeMounts: []
# - name: extra-volume
#   mountPath: /extra
#   readOnly: true