{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "amq.fullname" . }}
  labels:
    {{- include "amq.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "amq.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
{{- end }}