apiVersion: v1
kind: Service
metadata:
  name: {{ include "amq.fullname" . }}
  labels:
    {{- include "amq.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.config.api.httpEnabled }}
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: {{ .Values.service.http.protocol }}
      name: http
    {{- end }}
    {{- if .Values.config.api.grpcEnabled }}
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: {{ .Values.service.grpc.protocol }}
      name: grpc
    {{- end }}
    {{- if .Values.service.metrics.enabled }}
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "amq.selectorLabels" . | nindent 4 }}
---
# Headless service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: {{ include "amq.fullname" . }}-headless
  labels:
    {{- include "amq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    {{- if .Values.config.api.httpEnabled }}
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: {{ .Values.service.http.protocol }}
      name: http
    {{- end }}
    {{- if .Values.config.api.grpcEnabled }}
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: {{ .Values.service.grpc.protocol }}
      name: grpc
    {{- end }}
  selector:
    {{- include "amq.selectorLabels" . | nindent 4 }}